GROUP=com.vero
VERSION_NAME=0.11.3
VERSION_CODE=2
MAIN_ARTIFACT_ID=vero-transcoder
LEGACY_ARTIFACT_ID=vero-transcoder-legacy
MAIN_NAMESPACE=com.vero.transcoder
LEGACY_NAMESPACE=com.vero.transcoder.legacy
